policy_path: '{ROBOSTL_ROOT}/assets/models/g1/motion.pt'
xml_path: '{ROBOSTL_ROOT}/assets/g1_description/scene.xml'
simulation_duration: 10.0
simulation_dt: 0.002
control_decimation: 10
kps:
- 100
- 100
- 100
- 150
- 40
- 40
- 100
- 100
- 100
- 150
- 40
- 40
kds:
- 2
- 2
- 2
- 4
- 2
- 2
- 2
- 2
- 2
- 4
- 2
- 2
default_angles:
- -0.1
- 0.0
- 0.0
- 0.3
- -0.2
- 0.0
- -0.1
- 0.0
- 0.0
- 0.3
- -0.2
- 0.0
ang_vel_scale: 0.25
dof_pos_scale: 1.0
dof_vel_scale: 0.05
action_scale: 0.25
cmd_scale:
- 2.0
- 2.0
- 0.25
num_actions: 12
num_obs: 47
cmd_init:
- 1.0
- 0
- 0
ground_geom_names:
- terrain
- floor
stl:
  h_min: 0.6333062052726746
  max_tilt_deg: 9.143325567245483
  max_torque: 43.870223792266856
  zmp_margin: 0.0
  stability_margin: 0.0
  max_angular_velocity: 1.5596610360145564
  max_velocity_error: 0.6462790668010712
  min_foot_clearance: -0.04750008136034012
  max_action_delta: 1.2395782170295713
  enable_safety: true
  enable_stability: true
  enable_performance: false
  use_zmp: true
  evaluation_start_time: 1.0
  performance_start_time: 1.0
